name = "feglobal"
main = "feglobal-api/src/index.js"
compatibility_date = "2024-12-22"

[env.production.vars]
GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycbzTA-zP2JsP2V35vcmglKRZWwW_xT0_1k-kvvpAa6rbPrfJIY_2bvT9w_xaO9afb4d7/exec"
GOOGLE_SHEET_STUDY_URL = "https://script.google.com/macros/s/AKfycbzTA-zP2JsP2V35vcmglKRZWwW_xT0_1k-kvvpAa6rbPrfJIY_2bvT9w_xaO9afb4d7/exec"
